#!/usr/bin/env python3
"""Build a lightweight browser PAC from the latest kyoresuas/ru-direct release."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import urllib.request
from pathlib import Path

UPSTREAM_REPO = "kyoresuas/ru-direct"
LATEST_RELEASE_API = f"https://api.github.com/repos/{UPSTREAM_REPO}/releases/latest"
DEFAULT_ASSET = "ru-lite.domains.txt"
DEFAULT_PROXY = "SOCKS5 127.0.0.1:3128"
DEFAULT_CUSTOM_DOMAINS = "custom-direct-domains.txt"

DOMAIN_RE = re.compile(
    r"^(?=.{1,253}\.?$)"
    r"(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+"
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.?$",
    re.IGNORECASE,
)


def request_json(url: str) -> dict:
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "ru-direct-pac-builder/1.0",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        return json.load(response)


def request_text(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "ru-direct-pac-builder/1.0"},
    )
    with urllib.request.urlopen(req, timeout=60) as response:
        return response.read().decode("utf-8")


def normalize_domain(line: str) -> str | None:
    value = line.strip()

    if not value or value.startswith("#") or value.startswith("!"):
        return None

    # Accept plain lists as well as a few common rule-list syntaxes.
    for prefix in ("@@||", "||", "domain:", "DOMAIN,"):
        if value.startswith(prefix):
            value = value[len(prefix):]

    if value.endswith("^"):
        value = value[:-1]
    if value.startswith("*."):
        value = value[2:]

    value = value.lstrip(".").rstrip(".").lower()

    try:
        value = value.encode("idna").decode("ascii")
    except UnicodeError:
        return None

    return value if DOMAIN_RE.match(value) else None


def latest_asset(asset_name: str) -> tuple[dict, dict]:
    release = request_json(LATEST_RELEASE_API)

    for asset in release.get("assets", []):
        if asset.get("name") == asset_name:
            return release, asset

    available = ", ".join(a.get("name", "") for a in release.get("assets", []))
    raise RuntimeError(f"{asset_name!r} not found in latest release. Assets: {available}")


def render_pac(domains: list[str], proxy: str, source_url: str) -> str:
    domains_json = json.dumps(domains, ensure_ascii=True, separators=(",", ":"))
    proxy_json = json.dumps(proxy)

    return f"""// AUTO-GENERATED by build_pac.py. Do not edit manually.
// Upstream: {source_url}
// Lightweight by design: no dnsResolve(), no isInNet().

var PROXY_ROUTE = {proxy_json};
var DIRECT_DOMAINS = {domains_json};

var DIRECT_DOMAIN_SET = {{}};
for (var i = 0; i < DIRECT_DOMAINS.length; i++) {{
    DIRECT_DOMAIN_SET[DIRECT_DOMAINS[i]] = true;
}}

function isPrivateIPv4(host) {{
    var parts = host.split(".");
    if (parts.length !== 4) return false;

    var octets = [];
    for (var i = 0; i < 4; i++) {{
        if (!/^\\d+$/.test(parts[i])) return false;

        octets[i] = parseInt(parts[i], 10);
        if (octets[i] < 0 || octets[i] > 255) return false;
    }}

    return octets[0] === 10 ||
           octets[0] === 127 ||
           (octets[0] === 169 && octets[1] === 254) ||
           (octets[0] === 172 && octets[1] >= 16 && octets[1] <= 31) ||
           (octets[0] === 192 && octets[1] === 168);
}}

function isDirectHost(host) {{
    if (!host) return true;

    host = host.toLowerCase();
    if (host.charAt(host.length - 1) === ".") {{
        host = host.substring(0, host.length - 1);
    }}

    if (host === "localhost" || host === "::1" || isPrivateIPv4(host)) {{
        return true;
    }}

    if (host.length > 6 && host.substring(host.length - 6) === ".local") {{
        return true;
    }}

    // Match the exact hostname, then each parent domain.
    // foo.bar.example.ru -> foo.bar.example.ru -> bar.example.ru -> example.ru
    var candidate = host;
    while (candidate) {{
        if (DIRECT_DOMAIN_SET[candidate]) return true;

        var dot = candidate.indexOf(".");
        if (dot < 0) break;
        candidate = candidate.substring(dot + 1);
    }}

    return false;
}}

function FindProxyForURL(url, host) {{
    return isDirectHost(host) ? "DIRECT" : PROXY_ROUTE;
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--asset", default=DEFAULT_ASSET)
    parser.add_argument("--proxy", default=DEFAULT_PROXY)
    parser.add_argument("--output", default="proxy.pac")
    parser.add_argument("--domains-output", default="domains.txt")
    parser.add_argument("--metadata-output", default="upstream.json")
    parser.add_argument("--custom-domains", default=DEFAULT_CUSTOM_DOMAINS)
    args = parser.parse_args()

    release, asset = latest_asset(args.asset)
    source_url = asset["browser_download_url"]
    raw = request_text(source_url)

    upstream_domains = {
        domain
        for line in raw.splitlines()
        if (domain := normalize_domain(line)) is not None
    }

    custom_domains = set()
    custom_path = Path(args.custom_domains)
    if custom_path.exists():
        custom_domains = {
            domain
            for line in custom_path.read_text(encoding="utf-8").splitlines()
            if (domain := normalize_domain(line)) is not None
        }

    domains = sorted(upstream_domains | custom_domains)

    if not domains:
        raise RuntimeError("No valid domains found; refusing to overwrite PAC")

    pac = render_pac(domains, args.proxy, source_url)

    Path(args.output).write_text(pac, encoding="utf-8")
    Path(args.domains_output).write_text("\n".join(domains) + "\n", encoding="utf-8")

    metadata = {
        "upstream_repository": UPSTREAM_REPO,
        "release_id": release.get("id"),
        "release_tag": release.get("tag_name"),
        "release_name": release.get("name"),
        "release_updated_at": release.get("updated_at"),
        "asset_id": asset.get("id"),
        "asset_name": asset.get("name"),
        "asset_size": asset.get("size"),
        "asset_digest": asset.get("digest"),
        "source_url": source_url,
        "upstream_domain_count": len(upstream_domains),
        "custom_domain_count": len(custom_domains),
        "domain_count": len(domains),
        "pac_sha256": hashlib.sha256(pac.encode("utf-8")).hexdigest(),
    }
    Path(args.metadata_output).write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(
        f"Generated {args.output}: {len(domains)} direct domains "
        f"({len(upstream_domains)} upstream + {len(custom_domains)} custom) "
        f"from {release.get('name') or release.get('tag_name')}"
    )


if __name__ == "__main__":
    main()
